spring:
  profiles:
    active:
      - dog
      - EN
      - prod
guru:
  username: YmlUserName
  password: YmlPassword
  jdbcurl: YmlUrlToDb

---
spring:
  profile: prod
guru:
  username: YmlProdUserName
  password: YmlProdPassword
  jdbcurl: YmlProdUrlToDb
