spring:
  profiles:
    active:
      - dog
      - EN
      - prod
guru:
  username: YmlUserName
  password: YmlPassword
  jbcurl: YmlUrlToDb

---
spring:
  profile: prod
guru:
  username: YmlProdUserName
  password: YmlProdPassword
  jbcurl: YmlProdUrlToDb
